import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PageTransition from "../../components/PageTransition";
import MarbleOverlay from "../../components/Overlay"; // ✅ 배경 추가

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >


        {/* ✅ 그 위에 페이지 콘텐츠 전환 */}
        <PageTransition>{children}</PageTransition>
             
             
     {/* ✅ 배경 먼저 깔고 */}
      <MarbleOverlay />
      </body>
    </html>
  );
}
