import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import PageTransition from "../../components/PageTransition";
import MarbleOverlay from "../../components/Overlay";
import BottomNav from "../../components/BottomNav"; // ✅ 추가

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        suppressHydrationWarning={true}
      >
        {/* ✅ 메인 콘텐츠 */}
        <div className="relative min-h-screen w-full max-w-[430px] mx-auto pb-[64px]">
          <PageTransition>{children}</PageTransition>
        </div>

        {/* ✅ 하단바 고정 */}
        <BottomNav />

        {/* ✅ MarbleOverlay는 최하단 */}
        <MarbleOverlay />
      </body>
    </html>
  );
}
