-- update_notes: 홈 상단 배너에 노출할 업데이트 노트.
-- 운영자는 Supabase Dashboard → Table editor 에서 row 추가/수정/비활성화.
-- 앱은 /api/update-notes (service role) 를 거쳐서 읽으므로 RLS 활성 + 정책 0 으로 둠.
-- → service role 만 통과, anon/authenticated 키로는 직접 접근 불가 (보안).

create table if not exists public.update_notes (
  id           bigint generated by default as identity primary key,
  title        text not null,
  body         text,
  published_at timestamptz not null default now(),
  is_active    boolean not null default true
);

create index if not exists update_notes_published_idx
  on public.update_notes (published_at desc)
  where is_active;

alter table public.update_notes enable row level security;
